[package]
name = "basic_example"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
axum.workspace = true
axum-server.workspace = true

serde.workspace = true

tokio.workspace = true

dashboard.workspace = true
